modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="levelable_tinkers_tools"
version="1.1.0"
displayName="Levelable Tinkers Tools"
logoFile="icon.png"
authors="xianmouyin"
description="..."

[[dependencies.levelable_tinkers_tools]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.levelable_tinkers_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.levelable_tinkers_tools]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.3.3.332,)"
    ordering="NONE"
    side="BOTH"
